apiVersion: v1
kind: Service
metadata:
  name: inference-service
  namespace: ai-nids
spec:
  type: NodePort
  selector:
    app: inference
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 30007