apiVersion: apps/v1
kind: Deployment
metadata:
  name: streaming
  namespace: ai-nids
spec:
  replicas: 1
  selector:
    matchLabels:
      app: streaming
  template:
    metadata:
      labels:
        app: streaming
    spec:
      containers:
      - name: streaming
        image: ai-nids-streaming:latest
        imagePullPolicy: Never