apiVersion: apps/v1
kind: Deployment
metadata:
  name: ingestion
  namespace: ai-nids
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ingestion
  template:
    metadata:
      labels:
        app: ingestion
    spec:
      containers:
      - name: ingestion
        image: ai-nids-ingestion:latest
        imagePullPolicy: Never